---
application:
  name: "sample"
  project: "sample"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "sample-db"
  version: "11"
routers:
- name: "main-sample"
  routes:
  - application_name: "sample"
    paths:
    - "/*"
