---
application:
  name: "qovery-test"
  project: "test"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "test-db"
  version: "12"
routers:
- name: "main-qovery-test"
  routes:
  - application_name: "qovery-test"
    paths:
    - "/*"
